name: publish

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  version_prefix: 0.0

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    name: publish

    steps:
      - uses: actions/checkout@v3

      - name: Setup Dot Net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ vars.DOTNET_VERSION }}

      - name: Restore Dependencies
        run: dotnet restore src/

      - name: Build
        run: dotnet build src/ -c Release
      
      - name: Pack
        run: dotnet pack src/cole.key-vault-diff/cole.key-vault-diff.csproj /p:Version=${{ env.version_prefix }}.${{ github.run_number }} /p:PackageVersion=${{ env.version_prefix }}.${{ github.run_number }} -c Release -o package

      - name: Publish
        with:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push package/*.nupkg --source https://api.nuget.org/v3/index.json --api-key $NUGET_API_KEY