name: pr-verify

on:
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    name: pr-verify
    
    steps:
      - uses: actions/checkout@v3

      - name: Setup Dot Net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ vars.DOTNET_VERSION }}

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release

      - name: Start containers
        run: docker-compose up -d

      - name: Run Tests
        run: dotnet test -c Release

      